version: "3"

services:
    repltile_1:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: php_repltile_1
        image: php:yuanjiyun_php_fpm_dev
        restart: always
        volumes:
            - ./:/var/www/html

    repltile_2:
        container_name: php_repltile_2
        image: php:yuanjiyun_php_fpm_dev
        restart: always
        volumes:
            - ./:/var/www/html

    repltile_3:
        container_name: php_repltile_3
        image: php:yuanjiyun_php_fpm_dev
        restart: always
        volumes:
            - ./:/var/www/html
