version: "3"

services:
    nginx:
        container_name: yuanjiyun_ngin_dev
        image: nginx:1.24.0-alpine
        ports:
            - "8101:80"
        restart: always
        tty: true
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/conf.d:/etc/nginx/conf.d

    php-fpm:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: yuanjiyun_php_fpm_dev
        image: php:yuanjiyun_php_fpm_dev
        depends_on:
            - nginx
        restart: always
        volumes:
            - ./:/var/www/html
