<?php

namespace App\Providers;

use App\Services\Auth\ApiGuard;
use App\Services\Auth\PhoneVerifyCodeUserProvider;
use App\Services\JsonWebToken\JWT;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Auth;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The model to policy mappings for the application.
     *
     * @var array<class-string, class-string>
     */
    protected $policies = [
        //
    ];

    /**
     * 所有需要注册的容器绑定
     *
     * @var array
     */
    public array $bindings = [];

    /**
     * 所有需要注册的容器单例
     *
     * @var array
     */
    public array $singletons = [
    ];

    /**
     * 注册任意应用程序验证 / 授权服务
     */
    public function boot(): void
    {
        Auth::extend('custom-jwt', function (Application $app, string $name, array $config) {
            // 返回 Illuminate\Contracts\Auth\Guard 的实例
            return ApiGuard::setClass($name, Auth::createUserProvider($config['provider']));
        });

        Auth::provider('phone-verify-Code', function (Application $app, array $config) {
            return new PhoneVerifyCodeUserProvider($app['hash'], $config['model']);
        });
    }

    /**
     * 注册应用服务
     *
     * @return void
     */
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
